// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("axmlprinter")>]
[<assembly: AssemblyProductAttribute("axmlprinter")>]
[<assembly: AssemblyDescriptionAttribute("Unpacker for Android binary XML (AXML) format")>]
[<assembly: AssemblyVersionAttribute("1.0.4")>]
[<assembly: AssemblyFileVersionAttribute("1.0.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "axmlprinter"
    let [<Literal>] AssemblyProduct = "axmlprinter"
    let [<Literal>] AssemblyDescription = "Unpacker for Android binary XML (AXML) format"
    let [<Literal>] AssemblyVersion = "1.0.4"
    let [<Literal>] AssemblyFileVersion = "1.0.4"
